spring:
  application:
    name: mt
  liquibase:
    enabled: true
    contexts: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dicie?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dicie
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
logging:
  level:
    root: INFO
mt:
  root-uri: http://localhost:8080
  version: @project.version@
  app:
    jwtSecret: mtSecretKey
    jwtExpirationMs: 86400000
---
spring:
  config:
    activate:
      on-profile: prod
mt:
  root-uri: http://165.232.96.113:8080